name: 'Second'
description: 'Second pass'
inputs:
  arg:
    description: 'The argument'
    required: true
    default: 'ismael'
outputs:
  out:
    description: 'Digested arg'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.arg }}
